namespace: dev

apigateway:
  image: __ECR_REGISTRY__/spring-petclinic-api-gateway #iguetoulene/spring-petclinic-api-gateway
  version: latest
  replicaCount: 2

customersservice:
  image: __ECR_REGISTRY__/spring-petclinic-customers-service #iguetoulene/spring-petclinic-customers-service
  version: latest
  replicaCount: 1
  database:
    host: customer-db.czoc8a8mks78.eu-west-3.rds.amazonaws.com:3306
    name: customersdb
    username: petclinic
    password: redacted

vetsservice:
  image: __ECR_REGISTRY__/spring-petclinic-vets-service #iguetoulene/spring-petclinic-vets-service
  version: latest
  replicaCount: 1
  database:
    host: vet-db.czoc8a8mks78.eu-west-3.rds.amazonaws.com:3306
    name: vetsdb
    username: petclinic
    password: redacted

visitsservice:
  image: __ECR_REGISTRY__/spring-petclinic-visits-service #iguetoulene/spring-petclinic-visits-service
  version: latest
  replicaCount: 1
  database:
    host: visit-db.czoc8a8mks78.eu-west-3.rds.amazonaws.com:3306
    name: visitsdb
    username: petclinic
    password: redacted