namespace: production

apigateway:
  image: __ECR_REGISTRY__/spring-petclinic-api-gateway #iguetoulene/spring-petclinic-api-gateway
  version: __APIGATEWAY_VERSION__ #9339762518-5
  replicaCount: 2

customersservice:
  image: __ECR_REGISTRY__/spring-petclinic-customers-service #iguetoulene/spring-petclinic-customers-service
  version: __CUSTOMERSSERVICE_VERSION__ #9339664015-9
  replicaCount: 1
  database:
    host: customer-db.czoc8a8mks78.eu-west-3.rds.amazonaws.com:3306
    name: customersdb
    username: petclinic
    password: redacted

vetsservice:
  image: __ECR_REGISTRY__/spring-petclinic-vets-service #iguetoulene/spring-petclinic-vets-service
  version: __VETSSERVICE_VERSION__ #9339762516-6
  replicaCount: 1
  database:
    host: vet-db.czoc8a8mks78.eu-west-3.rds.amazonaws.com:3306
    name: vetsdb
    username: petclinic
    password: redacted

visitsservice:
  image: __ECR_REGISTRY__/spring-petclinic-visits-service #iguetoulene/spring-petclinic-visits-service
  version: __VISITSSERVICE_VERSION__ #9339762528-5
  replicaCount: 1
  database:
    host: visit-db.czoc8a8mks78.eu-west-3.rds.amazonaws.com:3306
    name: visitsdb
    username: petclinic
    password: redacted