namespace: production

apigateway:
  image: iguetoulene/spring-petclinic-api-gateway
  version: 9337591902-4
  replicaCount: 2

customersservice:
  image: iguetoulene/spring-petclinic-customers-service
  version: 9339446482-7
  replicaCount: 1

vetsservice:
  image: iguetoulene/spring-petclinic-vets-service
  version: 9338102378-3
  replicaCount: 1

visitsservice:
  image: iguetoulene/spring-petclinic-visits-service
  version: 9338111506-3
  replicaCount: 1

database:
  host: petclinic-db.czoc8a8mks78.eu-west-3.rds.amazonaws.com:3306
  name: petclinicdb
  username: petclinic
  password: redacted
