namespace: staging

apigateway:
  image: iguetoulene/spring-petclinic-api-gateway
  version: latest
  replicaCount: 1

customersservice:
  image: iguetoulene/spring-petclinic-customers-service
  version: latest
  replicaCount: 1

vetsservice:
  image: iguetoulene/spring-petclinic-vets-service
  version: latest
  replicaCount: 1

visitsservice:
  image: iguetoulene/spring-petclinic-visits-service
  version: latest
  replicaCount: 1

database:
  host: petclinic-db.czoc8a8mks78.eu-west-3.rds.amazonaws.com:3306
  name: petclinic-db
  username: petclinic
  password: redacted