namespace: staging

apigateway:
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-api-gateway #iguetoulene/spring-petclinic-api-gateway
  version: aws ecr describe-images --repository-name public.ecr.aws/i7s8l3z4/spring-petclinic-api-gateway --query "reverse(sort_by(imageDetails,& imagePushedAt))[0].imageTags[0]")
  replicaCount: 2

customersservice:
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-customers-service #iguetoulene/spring-petclinic-customers-service
  version: aws ecr describe-images --repository-name public.ecr.aws/i7s8l3z4/spring-petclinic-customers-service --query "reverse(sort_by(imageDetails,& imagePushedAt))[0].imageTags[0]")
  replicaCount: 1
  database:
    host: customer-db.c34i6uggo2hc.eu-west-3.rds.amazonaws.com:3306
    name: customersdb
    username: petclinic
    password: redacted

vetsservice:
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-vets-service #iguetoulene/spring-petclinic-vets-service
  version: aws ecr describe-images --repository-name public.ecr.aws/i7s8l3z4/spring-petclinic-vets-service --query "reverse(sort_by(imageDetails,& imagePushedAt))[0].imageTags[0]")
  replicaCount: 1
  database:
    host: vet-db.c34i6uggo2hc.eu-west-3.rds.amazonaws.com:3306
    name: vetsdb
    username: petclinic
    password: redacted

visitsservice:
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-visits-service  #iguetoulene/spring-petclinic-visits-service
  version: aws ecr describe-images --repository-name public.ecr.aws/i7s8l3z4/spring-petclinic-visits-service --query "reverse(sort_by(imageDetails,& imagePushedAt))[0].imageTags[0]")
  replicaCount: 1
  database:
    host: visit-db.c34i6uggo2hc.eu-west-3.rds.amazonaws.com:3306
    name: visitsdb
    username: petclinic
    password: redacted

adminserver:
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-admin-server
  version: latest
  replicaCount: 1

configserver:
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-config-server
  version: latest
  replicaCount: 1

discoveryserver:
  image: public.ecr.aws/i7s8l3z4/spring-petclinic-discovery-server
  version: latest
  replicaCount: 1