namespace: staging

apigateway:
  image: iguetoulene/spring-petclinic-api-gateway
  version: latest
  replicaCount: 1

customersservice:
  image: iguetoulene/spring-petclinic-customers-service
  version: latest
  replicaCount: 1

vetsservice:
  image: iguetoulene/spring-petclinic-vets-service
  version: latest
  replicaCount: 1

visitsservice:
  image: iguetoulene/spring-petclinic-visits-service
  version: latest
  replicaCount: 1

database:
  host: petclinic-db.c9mu0cykmyng.eu-west-3.rds.amazonaws.com:3306
  name: petclinicdb
  username: petclinic
  password: redacted