apiVersion: v1
kind: Service
metadata:
  labels:
    app: vets-service
  name: vets-service
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: vets-service
  ports:
  - name: "http"
    port: 80
    targetPort: 8080