name: Service Build Workflow to ECR
run-name: Starting to build ${{ inputs.service-name }}
on:
  workflow_call:
    inputs:
      service-name:
        required: true
        type: string

jobs:
  build-and-publish-service:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setting up Java for the Runner
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '11'
          cache: maven

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION_1 }}

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public
          region: ${{ secrets.AWS_REGION_1 }}

      - name: Build and push Docker images
        run: |
          # Vos commandes pour construire et pousser les images Docker

      - name: Update Image Versions in staging-values.yaml
        run: |
          chmod +x ./update-values.sh
          ./update-values.sh

      - name: Commit and push updated staging-values.yaml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add helmchart/staging-values.yaml
          git commit -m "Update image tags in staging-values.yaml" || echo "No changes to commit"
          git push origin main || echo "Nothing to push"

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f helmchart/staging-values.yaml
