name: Build and Deploy Vets Service

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    uses: ./.github/workflows/micro-service-build-to-ecr.yml
    with:
      service-name: 'spring-petclinic-vets-service'
      aws-region: ${{ secrets.AWS_REGION_1 }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
